"use client";

import { TurnstileWidget } from "@/components/turnstile-widget";
import { useState } from "react";

export function RecoveryForm(){
  const[identifier,setIdentifier]=useState("");const[token,setToken]=useState("");const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[stage,setStage]=useState<"request"|"verify"|"password">("request");const[turnstileToken,setTurnstileToken]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function requestCode(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/v1/auth/password-reset/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identifier,turnstileToken:turnstileToken||undefined})});const body=await response.json();setBusy(false);if(response.ok)setStage("verify");else setError(body.error?.message??"Unable to start recovery.")}
  async function verify(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/v1/auth/password-reset/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({identifier,token})});const body=await response.json();setBusy(false);if(response.ok)setStage("password");else setError(body.error?.message??"Invalid recovery code.")}
  async function complete(event:React.FormEvent){event.preventDefault();if(password!==confirm){setError("Passwords do not match.");return}setBusy(true);setError("");const response=await fetch("/api/v1/auth/password-reset/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const body=await response.json();if(response.ok)window.location.assign(body.data.next??"/home");else{setError(body.error?.message??"Unable to reset password.");setBusy(false)}}
  if(stage==="verify")return <form className="auth-form auth-form-stacked" onSubmit={verify}><p>If an account exists, a six-digit recovery code was sent.</p><label>Recovery code<input className="otp-input" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={token} onChange={event=>setToken(event.target.value.replace(/\D/g,"").slice(0,6))} required/></label>{error&&<p className="form-error">{error}</p>}<button className="button button-primary button-wide" disabled={busy||token.length!==6}>Verify code</button></form>;
  if(stage==="password")return <form className="auth-form auth-form-stacked" onSubmit={complete}><label>New password<input type="password" minLength={12} maxLength={72} autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} required/></label><label>Confirm password<input type="password" minLength={12} maxLength={72} autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)} required/></label>{error&&<p className="form-error">{error}</p>}<button className="button button-primary button-wide" disabled={busy}>Set new password</button></form>;
  return <form className="auth-form auth-form-stacked" onSubmit={requestCode}><label>Email or username<input autoComplete="username" value={identifier} onChange={event=>setIdentifier(event.target.value)} required/></label><TurnstileWidget onToken={setTurnstileToken}/>{error&&<p className="form-error">{error}</p>}<button className="button button-primary button-wide" disabled={busy}>Send recovery code</button></form>;
}
