import { createClient } from "@supabase/supabase-js";

const tokens=process.argv.slice(2);const args={};for(let i=0;i<tokens.length;i++){if(tokens[i]?.startsWith("--")){const key=tokens[i].slice(2);const next=tokens[i+1];if(next&&!next.startsWith("--")){args[key]=next;i++}else args[key]=true}}
const command=String(tokens.find(token=>!token.startsWith("--"))??"list");
const url=process.env.SUPABASE_URL??process.env.NEXT_PUBLIC_SUPABASE_URL;const secret=process.env.SUPABASE_SECRET_KEY;
if(!url||!secret){console.error("Set SUPABASE_URL and SUPABASE_SECRET_KEY in the operator environment.");process.exit(1)}
const db=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});const apply=args.apply===true;
const slug=String(args.campus??args.slug??"").trim().toLowerCase();
async function campus(){const{data,error}=await db.from("campuses").select("*").eq("slug",slug).maybeSingle();if(error)throw error;if(!data)throw new Error(`Campus '${slug}' was not found.`);return data}
async function audit(campusId,action,target,metadata={}){const{error}=await db.from("audit_log").insert({campus_id:campusId,actor_id:null,action,target_type:"campus",target_id:target,metadata:{operatorCommand:command,...metadata}});if(error)throw error}
async function preview(label,payload,mutation){console.log(`${apply?"APPLY":"PREVIEW"}: ${label}`);console.log(JSON.stringify(payload,null,2));if(!apply){console.log("Re-run with --apply after reviewing this preview.");return}await mutation();console.log("Applied. Read back with: pnpm campus:admin -- list")}
if(command==="list"){
  const{data,error}=await db.from("campuses").select("id,name,short_name,slug,city,region,country_code,timezone,status,campus_email_domains(domain,is_enabled)").order("name");if(error)throw error;console.log(JSON.stringify(data,null,2));
}else if(command==="upsert"){
  if(!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(slug)||!args.name)throw new Error("Usage: campus:admin -- upsert --campus campus-alpha --name 'Campus Alpha' [--short-name Alpha --timezone America/Chicago --city Testville --region TS] [--apply]");
  const{data:existing,error:existingError}=await db.from("campuses").select("id,status").eq("slug",slug).maybeSingle();if(existingError)throw existingError;if(existing&&existing.status!=="disabled")throw new Error("Refusing to modify an enabled or suspended campus with upsert. Change lifecycle state explicitly, then retry only if an inactive-record edit is intended.");
  const payload={slug,name:String(args.name),short_name:String(args["short-name"]??args.name),timezone:String(args.timezone??"America/Chicago"),city:args.city?String(args.city):null,region:args.region?String(args.region):null,country_code:String(args.country??"US").toUpperCase(),status:"disabled"};
  await preview(`create or update inactive campus ${slug}`,payload,async()=>{const{data,error}=await db.from("campuses").upsert(payload,{onConflict:"slug"}).select("id").single();if(error)throw error;await audit(data.id,"campus.operator_upsert",slug,{status:"disabled"})});
}else if(command==="status"){
  const target=await campus();const status=String(args.status??"");if(!["enabled","suspended","disabled"].includes(status))throw new Error("Choose --status enabled, suspended, or disabled.");
  if(status==="enabled"){const{count}=await db.from("campus_email_domains").select("domain",{count:"exact",head:true}).eq("campus_id",target.id).eq("is_enabled",true);if(!count)throw new Error("A campus needs at least one enabled domain before activation.")}
  await preview(`set ${slug} status to ${status}`,{before:target.status,after:status},async()=>{const{error}=await db.from("campuses").update({status}).eq("id",target.id);if(error)throw error;await audit(target.id,"campus.operator_status",slug,{before:target.status,after:status})});
}else if(command==="domain"){
  const target=await campus();const domain=String(args.domain??"").trim().toLowerCase();const action=String(args.action??"add");if(!domain||domain.includes("@")||domain.includes("*"))throw new Error("Provide an exact domain without @ or wildcards.");if(!["add","enable","disable","remove"].includes(action))throw new Error("Choose --action add, enable, disable, or remove.");
  if(["disable","remove"].includes(action)){const{data}=await db.from("campus_email_domains").select("domain").eq("campus_id",target.id).eq("is_enabled",true).neq("domain",domain);if(!data?.length&&args["confirm-last-domain"]!==true)throw new Error("Refusing to remove or disable the last enabled domain. Add --confirm-last-domain only after reviewing the registration impact.")}
  await preview(`${action} domain ${domain} for ${slug}`,{campus:slug,domain,action},async()=>{let error;if(action==="remove")({error}=await db.from("campus_email_domains").delete().eq("campus_id",target.id).eq("domain",domain));else if(action==="disable")({error}=await db.from("campus_email_domains").update({is_enabled:false}).eq("campus_id",target.id).eq("domain",domain));else({error}=await db.from("campus_email_domains").upsert({campus_id:target.id,domain,is_enabled:true},{onConflict:"campus_id,domain"}));if(error)throw error;await audit(target.id,"campus.operator_domain",slug,{domain,action})});
}else if(command==="setting"){
  const key=String(args.key??"");const allowed={network_features_enabled:"boolean",message_request_daily_limit:"integer",message_request_decline_cooldown_days:"integer",blocked_conversation_visibility:"mode"};if(!allowed[key])throw new Error(`Allowed settings: ${Object.keys(allowed).join(", ")}`);let value;if(allowed[key]==="boolean"){if(!["true","false"].includes(String(args.value)))throw new Error("Boolean setting requires --value true or false.");value=String(args.value)==="true"}else if(allowed[key]==="integer"){value=Number(args.value);if(!Number.isInteger(value)||value<0||value>1000)throw new Error("Integer setting must be between 0 and 1000.")}else{value=String(args.value);if(!["read_only","hidden"].includes(value))throw new Error("Visibility mode must be read_only or hidden.")}
  await preview(`update runtime setting ${key}`,{key,value},async()=>{const{error}=await db.from("runtime_settings").upsert({key,value},{onConflict:"key"});if(error)throw error;const first=(await db.from("campuses").select("id").order("created_at").limit(1).single()).data;if(first)await audit(first.id,"runtime_setting.operator_update",key,{value})});
}else if(command==="platform-role"){
  const username=String(args.username??"").toLowerCase();const role=String(args.role??"moderator");const action=String(args.action??"grant");if(!username||!["moderator","admin"].includes(role)||!["grant","revoke"].includes(action))throw new Error("Usage: platform-role --username handle --role moderator|admin --action grant|revoke [--apply]");const{data:profile,error}=await db.from("profiles").select("id,campus_id,handle").eq("handle",username).single();if(error)throw error;
  await preview(`${action} platform ${role} for @${username}`,{profileId:profile.id,role,action},async()=>{let error;if(action==="grant")({error}=await db.from("platform_role_assignments").upsert({profile_id:profile.id,role},{onConflict:"profile_id,role"}));else({error}=await db.from("platform_role_assignments").delete().eq("profile_id",profile.id).eq("role",role));if(error)throw error;await audit(profile.campus_id,`platform_role.operator_${action}`,profile.id,{role})});
}else{throw new Error("Commands: list, upsert, status, domain, setting, platform-role")}
