import { createSupabaseServerClient } from "./supabase/server";

export async function loadListings(filters?:{q?:string;category?:string;sort?:string;limit?:number}) {
  try { const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)return [];let query=db.from("listings").select("id,title,description,category,condition,price_cents,currency,status,created_at,profiles!listings_seller_id_fkey(handle,display_name),media_uploads(id,alt_text,status)").eq("status","active").is("deleted_at",null).limit(filters?.limit??24);if(filters?.q)query=query.textSearch("search_vector",filters.q,{type:"websearch",config:"english"});if(filters?.category)query=query.eq("category",filters.category);if(filters?.sort==="price_asc")query=query.order("price_cents",{ascending:true}).order("id",{ascending:true});else if(filters?.sort==="price_desc")query=query.order("price_cents",{ascending:false}).order("id",{ascending:false});else query=query.order("created_at",{ascending:false}).order("id",{ascending:false});const {data,error}=await query;return error?[]:data??[]; } catch { return []; }
}

type MarketplaceCursor={sort:"newest"|"price_asc"|"price_desc";value:string;id:string};
function decodeMarketplaceCursor(value?:string):MarketplaceCursor|null{if(!value)return null;try{const parsed=JSON.parse(Buffer.from(value,"base64url").toString("utf8")) as MarketplaceCursor;if(!["newest","price_asc","price_desc"].includes(parsed.sort)||!/^[0-9a-f-]{36}$/i.test(parsed.id))return null;if(parsed.sort==="newest"&&Number.isNaN(Date.parse(parsed.value)))return null;if(parsed.sort!=="newest"&&!/^\d+$/.test(parsed.value))return null;return parsed}catch{return null}}
export async function loadMarketplacePage(filters?:{q?:string;category?:string;sort?:string;cursor?:string}){
  try{const db=await createSupabaseServerClient();const{data:{user}}=await db.auth.getUser();if(!user)return{listings:[],nextCursor:null};const sort=(filters?.sort==="price_asc"||filters?.sort==="price_desc"?filters.sort:"newest") as MarketplaceCursor["sort"];const cursor=decodeMarketplaceCursor(filters?.cursor);let query=db.from("listings").select("id,title,description,category,condition,price_cents,currency,status,created_at,profiles!listings_seller_id_fkey(handle,display_name),media_uploads(id,alt_text,status)").eq("status","active").is("deleted_at",null).limit(25);if(filters?.q)query=query.textSearch("search_vector",filters.q,{type:"websearch",config:"english"});if(filters?.category)query=query.eq("category",filters.category);if(sort==="price_asc")query=query.order("price_cents",{ascending:true}).order("id",{ascending:true});else if(sort==="price_desc")query=query.order("price_cents",{ascending:false}).order("id",{ascending:false});else query=query.order("created_at",{ascending:false}).order("id",{ascending:false});if(cursor?.sort===sort){if(sort==="newest")query=query.or(`created_at.lt.${cursor.value},and(created_at.eq.${cursor.value},id.lt.${cursor.id})`);else if(sort==="price_asc")query=query.or(`price_cents.gt.${cursor.value},and(price_cents.eq.${cursor.value},id.gt.${cursor.id})`);else query=query.or(`price_cents.lt.${cursor.value},and(price_cents.eq.${cursor.value},id.lt.${cursor.id})`)}const{data,error}=await query;if(error)return{listings:[],nextCursor:null};const rows=data??[];const listings=rows.slice(0,24);const last=listings.at(-1);const nextCursor=rows.length>24&&last?Buffer.from(JSON.stringify({sort,value:sort==="newest"?last.created_at:String(last.price_cents),id:last.id} satisfies MarketplaceCursor),"utf8").toString("base64url"):null;return{listings,nextCursor}}catch{return{listings:[],nextCursor:null}}
}
export async function loadEvents() {
  try { const db=await createSupabaseServerClient();const {data:{user}}=await db.auth.getUser();if(!user)return [];const {data,error}=await db.from("events").select("id,title,description,location,starts_at,ends_at,capacity,event_rsvps(count)").is("cancelled_at",null).is("deleted_at",null).gte("starts_at",new Date().toISOString()).order("starts_at").limit(12);return error?[]:data??[]; } catch { return []; }
}
