"use client";

import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { ArrowLeft, Ban, Check, LoaderCircle, MessageCircle, Search, X } from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { UserAvatar } from "@/components/user-avatar";

type Conversation={id:string;listing_id:string|null;listing_title:string|null;event_id:string|null;event_title:string|null;last_message_at:string;other_profile_id:string;other_handle:string;other_display_name:string|null;other_avatar_id:string|null;other_campus_name:string;other_campus_short_name:string;latest_body:string|null;latest_created_at:string|null;unread_count:number|string;is_blocked:boolean};
type Message={id:string;sender_id:string;body:string;created_at:string};
type RequestPerson={id:string;username:string;displayName:string|null;avatarId:string|null;campusName:string;campusShortName:string;joinedMonth:string};
type RequestRow={id:string;requesterId:string;recipientId:string;status:string;openingMessage:string;createdAt:string;respondedAt:string|null;contextType:string;listingId:string|null;eventId:string|null;person:RequestPerson};

export function MessagesClient(){
  const params=useSearchParams();const requestedConversation=params.get("conversation")??"";const initialView=params.get("view")??"conversations";
  const[view,setView]=useState(initialView);const[conversations,setConversations]=useState<Conversation[]>([]);const[incoming,setIncoming]=useState<RequestRow[]>([]);const[sent,setSent]=useState<RequestRow[]>([]);const[selected,setSelected]=useState("");const[messages,setMessages]=useState<Message[]>([]);const[currentUser,setCurrentUser]=useState("");const[body,setBody]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  const loadInbox=useCallback(async()=>{const[cr,ir,sr]=await Promise.all([fetch("/api/v1/conversations"),fetch("/api/v1/conversation-requests?box=incoming"),fetch("/api/v1/conversation-requests?box=sent")]);const[cb,ib,sb]=await Promise.all([cr.json(),ir.json(),sr.json()]);if(cr.ok){const rows=cb.data??[];setConversations(rows);setSelected(value=>value||(rows.some((row:Conversation)=>row.id===requestedConversation)?requestedConversation:"")||(!window.matchMedia("(max-width: 767px)").matches?rows[0]?.id??"":""));}if(ir.ok)setIncoming(ib.data??[]);if(sr.ok)setSent(sb.data??[]);setLoading(false)},[requestedConversation]);
  useEffect(()=>{createSupabaseBrowserClient().auth.getUser().then(({data})=>setCurrentUser(data.user?.id??""));void loadInbox()},[loadInbox]);
  useEffect(()=>{if(!selected){setMessages([]);return}let live=true;async function load(){const response=await fetch(`/api/v1/conversations/${selected}/messages`);const result=await response.json();if(response.ok&&live){setMessages([...(result.data??[])].reverse());await fetch(`/api/v1/conversations/${selected}/read`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"})}else if(!response.ok)setError(result.error?.message??"Unable to load messages.")}void load();const client=createSupabaseBrowserClient();const channel=client.channel(`conversation:${selected}`,{config:{private:true}}).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${selected}`},()=>void load()).subscribe();return()=>{live=false;void client.removeChannel(channel)}},[selected]);
  const active=useMemo(()=>conversations.find(item=>item.id===selected),[conversations,selected]);
  async function respond(id:string,responseValue:"accepted"|"declined"){setError("");const response=await fetch(`/api/v1/conversation-requests/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({response:responseValue})});const result=await response.json();if(response.ok){await loadInbox();if(result.data?.conversationId){setView("conversations");setSelected(result.data.conversationId)}}else setError(result.error?.message??"This request is no longer available.")}
  async function cancel(id:string){const response=await fetch(`/api/v1/conversation-requests/${id}`,{method:"DELETE"});if(response.ok)await loadInbox();else setError("This request can no longer be cancelled.")}
  async function block(profileId:string){const response=await fetch(`/api/v1/blocks/${profileId}`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});if(response.ok)await loadInbox();else setError("Unable to block this member.")}
  async function report(id:string){const response=await fetch("/api/v1/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetType:"conversation_request",targetId:id,reason:"other",details:"Reported from incoming message requests.",idempotencyKey:crypto.randomUUID()})});if(response.ok)setError("Report submitted for review.");else setError("Unable to submit this report.")}
  async function send(event:React.FormEvent){event.preventDefault();if(!active||active.is_blocked||!body.trim())return;const text=body.trim();setBody("");const response=await fetch(`/api/v1/conversations/${active.id}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:text,idempotencyKey:crypto.randomUUID()})});const result=await response.json();if(response.ok)setMessages(items=>items.some(item=>item.id===result.data.id)?items:[...items,result.data]);else{setBody(text);setError(result.error?.message??"Unable to send message.")}}
  if(loading)return <main className="center-state"><LoaderCircle className="spin"/>Loading conversations…</main>;
  const requests=view==="incoming"?incoming:sent;
  return <main className={`messages-page${selected?" has-selection":""}`}>
    <section className="conversation-list">
      <div className="messages-head"><span className="overline">PRIVATE & VERIFIED</span><h1>Messages</h1><div className="request-tabs"><button className={view==="conversations"?"active":""} onClick={()=>setView("conversations")}>Conversations</button><button className={view==="incoming"?"active":""} onClick={()=>setView("incoming")}>Incoming ({incoming.filter(item=>item.status==="pending").length})</button><button className={view==="sent"?"active":""} onClick={()=>setView("sent")}>Sent</button></div><Link className="button button-ghost button-small" href="/people"><Search/>Find people</Link></div>
      {view!=="conversations" ? <div className="request-list"><h2>{view==="incoming"?"Incoming requests":"Sent requests"}</h2>{requests.length?requests.map(request=><article key={request.id}><UserAvatar name={request.person.displayName??request.person.username} mediaId={request.person.avatarId}/><div><Link href={`/u/${request.person.username}`}><strong>{request.person.displayName??request.person.username}</strong></Link><span>@{request.person.username} · {request.person.campusShortName??request.person.campusName}</span><p className="request-opening">{request.openingMessage}</p><small>{view==="sent"&&request.status==="unavailable"?"This request is unavailable.":request.status}</small></div>{view==="incoming"&&request.status==="pending"&&<><button aria-label="Accept" onClick={()=>respond(request.id,"accepted")}><Check/></button><button aria-label="Decline" onClick={()=>respond(request.id,"declined")}><X/></button><button aria-label="Report" onClick={()=>report(request.id)}>Report</button><button aria-label="Block" onClick={()=>block(request.person.id)}><Ban/></button></>}{view==="sent"&&request.status==="pending"&&<button onClick={()=>cancel(request.id)}>Cancel</button>}</article>):<div className="empty-state compact"><p>No {view} requests.</p></div>}</div> : <>{!conversations.length&&<div className="empty-state"><MessageCircle/><h2>No conversations yet</h2><p>Find a member or open a listing to send a request.</p></div>}{conversations.map(conversation=><button key={conversation.id} className={`conversation-row ${conversation.id===selected?"selected":""}`} onClick={()=>setSelected(conversation.id)}><UserAvatar name={conversation.other_display_name??conversation.other_handle} mediaId={conversation.other_avatar_id}/><div><span><strong>{conversation.other_display_name??conversation.other_handle}</strong><small>{new Date(conversation.latest_created_at??conversation.last_message_at).toLocaleDateString()}</small></span><em>{conversation.latest_body??conversation.listing_title??conversation.event_title??"Conversation ready"}</em><small>{conversation.other_campus_short_name??conversation.other_campus_name}{conversation.is_blocked?" · Read only":""}</small></div>{Number(conversation.unread_count)>0&&<b className="nav-badge">{conversation.unread_count}</b>}</button>)}</>}
    </section>
    <section className="chat-panel">{active?<><header><button type="button" className="mobile-thread-back" aria-label="Back" onClick={()=>setSelected("")}><ArrowLeft/></button><UserAvatar name={active.other_display_name??active.other_handle} mediaId={active.other_avatar_id}/><div><strong>{active.other_display_name??active.other_handle}</strong><small>{active.listing_title??active.event_title??`@${active.other_handle}`} · {active.other_campus_short_name??active.other_campus_name}</small></div>{!active.is_blocked&&<button type="button" className="thread-block" onClick={()=>block(active.other_profile_id)}><Ban/>Block</button>}</header>{active.is_blocked&&<div className="trade-banner"><Ban/><div><strong>This conversation is read only</strong><span>History is preserved, but no new messages can be sent.</span></div></div>}<div className="message-stream">{messages.map(message=><div key={message.id} className={`bubble ${message.sender_id===currentUser?"mine":"theirs"}`}>{message.body}<small>{new Date(message.created_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</small></div>)}</div><form className="message-composer" onSubmit={send}><input aria-label="Write a message" placeholder={active.is_blocked?"Messaging is disabled":"Write a message…"} value={body} onChange={event=>setBody(event.target.value)} maxLength={4000} disabled={active.is_blocked}/><button className="button button-primary" disabled={active.is_blocked||!body.trim()}>Send</button></form></>:<div className="empty-state"><MessageCircle/><h2>Select a conversation</h2></div>}{error&&<p className="form-error message-error" role="status">{error}</p>}</section>
  </main>;
}
