"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, CalendarDays, Home, LogOut, MessageCircle, Plus, Search, Settings, ShieldCheck, ShoppingBag } from "lucide-react";
import { useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { Brand } from "./brand";
import { ThemeToggle } from "./theme-toggle";
import { UserAvatar } from "./user-avatar";

type Props={profile:{id:string;handle:string;displayName:string;avatarId:string|null};isStaff:boolean;notificationCount:number;messageCount:number};
export function AppNavigation({profile,isStaff,notificationCount:initialNotificationCount,messageCount}:Props){
  const path=usePathname();const[notificationCount,setNotificationCount]=useState(initialNotificationCount);const active=(href:string)=>path===href||path.startsWith(`${href}/`);
  useEffect(()=>setNotificationCount(initialNotificationCount),[initialNotificationCount]);
  useEffect(()=>{const client=createSupabaseBrowserClient();const refresh=async()=>{const{count}=await client.from("notifications").select("id",{count:"exact",head:true}).is("read_at",null);setNotificationCount(count??0)};const readAll=()=>setNotificationCount(0);const readOne=()=>setNotificationCount(value=>Math.max(0,value-1));window.addEventListener("campus:notifications-read",readAll);window.addEventListener("campus:notification-read",readOne);const channel=client.channel(`notification:${profile.id}`,{config:{private:true}}).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:`profile_id=eq.${profile.id}`},()=>void refresh()).subscribe();return()=>{window.removeEventListener("campus:notifications-read",readAll);window.removeEventListener("campus:notification-read",readOne);void client.removeChannel(channel)}},[profile.id]);
  async function logout(){await fetch("/api/v1/auth/logout",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});if("caches"in window){for(const key of await caches.keys())await caches.delete(key)}window.location.assign("/sign-in")}
  const avatar=<UserAvatar name={profile.displayName} mediaId={profile.avatarId}/>;
  return <><aside className="sidebar"><Brand/><nav aria-label="Campus Exchange"><Link className={`nav-item ${active("/home")?"active":""}`} href="/home"><Home/>Home</Link><Link className={`nav-item ${active("/marketplace")?"active":""}`} href="/marketplace"><ShoppingBag/>Marketplace</Link><Link className={`nav-item ${active("/events")?"active":""}`} href="/events"><CalendarDays/>Events</Link><Link className={`nav-item ${active("/messages")?"active":""}`} href="/messages"><MessageCircle/>Messages{messageCount>0&&<span className="nav-badge">{messageCount>99?"99+":messageCount}</span>}</Link><Link className={`nav-item ${active("/notifications")?"active":""}`} href="/notifications"><Bell/>Notifications{notificationCount>0&&<span className="nav-badge">{notificationCount>99?"99+":notificationCount}</span>}</Link></nav><div className="sidebar-bottom">{isStaff&&<Link className={`nav-item ${active("/admin")?"active":""}`} href="/admin"><ShieldCheck/>Moderation</Link>}<ThemeToggle/><Link className={`nav-item ${active("/settings")?"active":""}`} href="/settings"><Settings/>Settings</Link><button className="nav-item nav-button" onClick={logout}><LogOut/>Log out</button><Link className="student-chip" href={`/u/${profile.handle}`}>{avatar}<div><strong>{profile.displayName}</strong><small>@{profile.handle}</small></div></Link></div></aside><header className="mobile-header"><Brand compact/><div><Link href="/marketplace" aria-label="Search"><Search/></Link><Link href="/notifications" aria-label="Notifications"><Bell/>{notificationCount>0&&<span className="nav-badge">{notificationCount}</span>}</Link></div></header><nav className="bottom-nav" aria-label="Mobile navigation"><Link className={active("/home")?"active":""} href="/home"><Home/><span>Home</span></Link><Link className={active("/marketplace")?"active":""} href="/marketplace"><ShoppingBag/><span>Market</span></Link><Link className="create-tab" href="/sell"><Plus/><span>Sell</span></Link><Link className={active("/events")?"active":""} href="/events"><CalendarDays/><span>Events</span></Link><Link className={active("/messages")?"active":""} href="/messages"><MessageCircle/><span>Chat</span></Link></nav></>;
}
