"use client";
import { LoaderCircle } from "lucide-react";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
export function CommunityForm() {
  const router=useRouter();const key=useRef(crypto.randomUUID());const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const slug=String(form.get("slug")??"").toLowerCase();const response=await fetch("/api/v1/discussions/communities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,displayName:form.get("displayName"),description:form.get("description"),rules:form.get("rules"),postingPermission:form.get("postingPermission"),idempotencyKey:key.current})});const result=await response.json().catch(()=>null);if(response.ok){router.push(`/discussions/c/${result.data.slug}`);router.refresh()}else{setError(result?.error?.message??"Unable to create this community.");setBusy(false)}}
  return <form className="listing-form discussion-form" onSubmit={submit}><section><h2>Community identity</h2><label>Display name<input name="displayName" minLength={3} maxLength={80} required placeholder="Campus Creators"/></label><label>Community slug<input name="slug" minLength={3} maxLength={32} pattern="[a-z0-9_]+" required placeholder="campus_creators"/><small>Lowercase letters, numbers, and underscores. This cannot be changed.</small></label><label>Description<textarea name="description" maxLength={5000} rows={5} placeholder="What should members discuss here?"/></label></section><section><h2>Rules and posting</h2><label>Community rules<textarea name="rules" maxLength={10000} rows={8} placeholder="1. Be respectful&#10;2. Keep posts relevant"/></label><label>Who can create posts?<select name="postingPermission" defaultValue="members"><option value="members">All active members</option><option value="moderators">Owners and moderators</option><option value="owner">Owner only</option></select></label></section>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-primary" disabled={busy}>{busy?<><LoaderCircle className="spin"/>Creating…</>:"Create community"}</button></form>;
}
