"use client";
import { LoaderCircle } from "lucide-react";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { maxImageBytes, normalizedImageType } from "@/lib/images";

export function DiscussionPostForm({ slug }: { slug: string }) {
  const router=useRouter();const key=useRef(crypto.randomUUID());const[postType,setPostType]=useState<"text"|"link"|"image">("text");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[progress,setProgress]=useState("");
  async function upload(file:File){const type=normalizedImageType(file.type,file.name);if(!type)throw new Error("Choose a JPEG, PNG, WebP, HEIC, or HEIF image.");if(file.size>maxImageBytes)throw new Error("Images must be 20 MB or smaller.");setProgress("Preparing private image upload…");const grant=await fetch("/api/v1/uploads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({purpose:"discussion_post",contentType:type,byteSize:file.size,altText:"Discussion post image"})});const grantBody=await grant.json();if(!grant.ok)throw new Error(grantBody.error?.message??"Unable to prepare the image.");setProgress("Validating and storing image…");const stored=await fetch(grantBody.data.uploadUrl,{method:"PUT",headers:{"content-type":type},body:file});const storedBody=await stored.json();if(!stored.ok)throw new Error(storedBody.error?.message??"Unable to upload the image.");return storedBody.data.id as string}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const form=new FormData(event.currentTarget);let mediaId:null|string=null;if(postType==="image"){const file=form.get("image");if(!(file instanceof File)||!file.size)throw new Error("Choose an image.");mediaId=await upload(file)}setProgress("Publishing post…");const response=await fetch(`/api/v1/discussions/communities/${slug}/posts`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({postType,title:form.get("title"),body:form.get("body")??"",linkUrl:postType==="link"?form.get("linkUrl"):null,mediaId,idempotencyKey:key.current})});const result=await response.json();if(!response.ok)throw new Error(result.error?.message??"Unable to publish this post.");router.push(`/discussions/c/${slug}/posts/${result.data.id}`);router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to publish this post.");setBusy(false);setProgress("")}}
  return <form className="listing-form discussion-form" onSubmit={submit}><section><h2>Post type</h2><div className="post-type-tabs">{(["text","link","image"] as const).map(type=><button type="button" className={postType===type?"active":""} onClick={()=>setPostType(type)} key={type}>{type}</button>)}</div><label>Title<input name="title" minLength={3} maxLength={300} required/></label>{postType!=="image"&&<label>Body<textarea name="body" rows={10} maxLength={20000} required={postType==="text"}/></label>}{postType==="link"&&<label>HTTPS link<input name="linkUrl" type="url" pattern="https://.*" required/></label>}{postType==="image"&&<label>Image<input name="image" type="file" accept="image/webp,image/png,image/jpeg,image/heic,image/heif,.heic,.heif" required/><small>Private JPEG, PNG, WebP, HEIC, or HEIF · 20 MB maximum</small></label>}</section>{progress&&<p className="form-notice" role="status">{progress}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button button-primary" disabled={busy}>{busy?<><LoaderCircle className="spin"/>Working…</>:"Publish post"}</button></form>;
}
